Course Work is done
Dmitriibeliaev97/CoursWork pull request #1
Opened 2023-03-06 13:08 UTC by Dmitriibeliaev97

2023-03-07 18:26 UTC, alekseykoshelev requested changes

2023-03-07 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        Fio[] fioBase = new Fio[10];
Массив должен быть полем класса, сейчас это переменная в методе

2023-03-07 18:26 UTC, alekseykoshelev commented on src/Main.java
> +    public static void isSumSalary (Employee[] arr) {
Когда массив будет полем, то аргумент можно будет убрать. 
Название метода странное, обычно используем is когда метод возвращает boolean.

2023-03-07 18:26 UTC, alekseykoshelev commented on src/Main.java
> +            averageSalary = (int) (total / arr.length);
Можно делать это после цикла, чтобы на каждой итерации не пересчитывать. Также можно сделать чтобы метод подсчета суммы возвращал число, чтобы здесь не дублировать код

2023-03-07 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        System.out.println(arr[0]);
Лучше лучше тогда использовать цикл)

2023-03-07 19:22 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        Fio[] fioBase = new Fio[10];
Не совсем понял. У мен же отдельный класс Fio. И массив инициализирован через конструктор в классе Fio. Не совсем понимаю, что нужно сделать

2023-03-07 19:53 UTC, Dmitriibeliaev97 commented on src/Main.java
> +            averageSalary = (int) (total / arr.length);
Сделал в методе подсчета месячной зарплаты и средней в месяц return.  Не знаю, это ли имелось ввиду, но методы стали короче, не дублируют друг друга и мне понравились)

2023-03-07 20:11 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        System.out.println(arr[0]);
Сделал)

2023-03-07 20:15 UTC, Dmitriibeliaev97 commented on src/Main.java
> +    public static void isSumSalary (Employee[] arr) {
Названия изменил

2023-03-08 18:19 UTC, alekseykoshelev commented on src/Main.java
> +        return total / arr.length;
А вот тут теперь можно сделать так `return sumSalary(arr) / arr.length` и все, это будет весь код метода. Переиспользуем метод подсчета суммы, чтобы код не дублировать.

2023-03-08 18:19 UTC, alekseykoshelev commented on src/Main.java
> +        Fio[] fioBase = new Fio[10];
Да, наверное, нужно было оставить коммент в другой строке. В общем имел ввиду, что массив Employee нужно сделать полем класса. Когда он будет полем, то у методов можно будет убрать аргумент и они смогут обращаться к полю.

2023-03-08 19:40 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        return total / arr.length;
Исправил)

2023-03-10 06:41 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        Fio[] fioBase = new Fio[10];
Вроде бы все понял, исправил)

2023-03-10 17:26 UTC, alekseykoshelev commented on src/Main.java
> +    public static double sumSalary (Employee[] employees) {
А теперь аргумент можно убрать и обращаться напрямую в массиву, который теперь поле в классе

2023-03-10 19:34 UTC, Dmitriibeliaev97 commented on src/Main.java
> +    public static double sumSalary (Employee[] employees) {
Сделал!)

2023-03-14 17:47 UTC, alekseykoshelev commented on src/Main.java
> +        Employee employeeWithMinSalary = employees[0];
А что, если сотрудников в данном отделе нет, тогда у тебя выведется информация о другом сотруднике. Тут можно изначальное значение сделать null, но тогда нужно будет добавить кое-какую проверку в 125 строке)

Аналогично и про максимум

2023-03-14 17:47 UTC, alekseykoshelev commented on src/Main.java
> +            averageSalaryByDepartment = total / counter;
Тут можно использовать уже существующий метод суммы по отделу, посчитать кол-во сотрудников в отделе придется конечно, но хотя бы не дублируем код суммирования)

2023-03-14 17:47 UTC, alekseykoshelev commented on src/Main.java
> +                System.out.println("Проиндексированная зарплата сотрудника " + employee.getFio() + ": " + newSalary);
Тут нужно кроме вывода вызвать сеттер, чтобы именно поменять значение зарплаты, сейчас ты его просто вывел в консоль

2023-03-14 19:39 UTC, Dmitriibeliaev97 commented on src/Main.java
> +                System.out.println("Проиндексированная зарплата сотрудника " + employee.getFio() + ": " + newSalary);
Сделал!

2023-03-14 19:52 UTC, Dmitriibeliaev97 commented on src/Main.java
> +            averageSalaryByDepartment = total / counter;
Не совсем понимаю, как можно один метод использовать в другом. При вызове метода суммы по отделу у меня выводится sout. Я же не могу это поделить на counter. Отдельную переменную из одного метода я ведь тоже не могу вызвать в другом методе. Изначально тоже думал, как уже использовать существующий метод суммы, но так и не придумал, пришлось дублировать

2023-03-14 20:03 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        Employee employeeWithMinSalary = employees[0];
Здесь, что бы я не делал, выдаёт такую ошибку.
Exception in thread "main" java.lang.NullPointerException
	at Main.minSalaryByDepartment(Main.java:125)
	at Main.main(Main.java:69)
я так понимаю, это из-за того, что я неправильно делаю проверку. Я так понял, надо проверить, есть ли сотрудники в данном отделе, а иначе вывести ошибку. Но не понял, как это записать

2023-03-16 18:18 UTC, alekseykoshelev commented on src/Main.java
> +            averageSalaryByDepartment = total / counter;
``Да, сейчас у тебя этот метод void (`public static void sumSalaryByDepartment (int department)`). Можно поменять его на int и использовать. sout можно из него убрать. Идея такая, что мы вызываем этот метод чтобы посчитать сумму в ЗП в отделе, только сумму. А внутри метода мы считаем количество сотрдуников в данном отделе. Полученную сумму делим на количество. Ты уже делал такой метод 
```
 public static double averageSalary () {
        return sumSalary() / employees.length;
    }

```

2023-03-16 18:20 UTC, alekseykoshelev commented on src/Main.java
> +        Employee employeeWithMinSalary = employees[0];
Тут нужно в строке 125 добавить проверку `if (employeeWithMinSalary  == null || employee.getSalary() < employeeWithMinSalary.getSalary())`. В таком виде будет работать, но нужно учесть, что переменная `employeeWithMinSalary` может остаться null, если в отделе нет сотрудников.

2023-03-16 20:04 UTC, Dmitriibeliaev97 commented on src/Main.java
> +        Employee employeeWithMinSalary = employees[0];
А я пытался это сделать отдельными if-ами, поэтому и не получалось. Так же добавил else, когда в отделе нет сотрудников, чтобы выдавал не ошибку а сообщение о том, что сотрудников нет

2023-03-16 20:21 UTC, Dmitriibeliaev97 commented on src/Main.java
> +            averageSalaryByDepartment = total / counter;
Всё понял, сделал) 
Единственное, теперь с методом подсчета суммы зп не вывести сразу номер отдела, мне с ни визуально больше нравилось) Это можно как-то исправить?

2023-09-09 14:33 UTC, merged